import React, { useEffect, useMemo, useState } from 'react';
import { API_BASE, getToken } from '../services/api';

// Build a tiny single-page PDF as a data URL so we can stuff it into an iframe
// without needing any external file. Generated entirely from the doc metadata.
function buildPdfDataUrl(doc) {
  // Strip anything outside printable ASCII so the result survives btoa (Latin1 only)
  // and the PDF content stream stays inside the safe range we built.
  const safe = (s) =>
    String(s == null ? '' : s)
      .replace(/[^\x20-\x7e]/g, '?')
      .replace(/[()\\]/g, ' ')
      .slice(0, 100);
  const title = safe(doc.name || 'Untitled Document');
  const subtitle = `Doc ID: ${safe(doc.doc_id)}  -  Deal: ${safe(doc.deal_id)}  -  Category: ${safe(doc.category)}`;
  const body = [
    'This is a placeholder PDF rendering generated by the M and A Deal Room VDR Viewer.',
    'In production this iframe would stream the secured original document.',
    'Use the Q and A panel on the right to ask the seller a question tied to this deal.',
  ];

  // Hand-rolled minimal PDF 1.4 — single page, Helvetica.
  const lines = [];
  lines.push('BT /F1 18 Tf 50 750 Td (' + title + ') Tj ET');
  lines.push('BT /F1 11 Tf 50 720 Td (' + subtitle + ') Tj ET');
  let y = 680;
  for (const ln of body) {
    lines.push('BT /F1 12 Tf 50 ' + y + ' Td (' + safe(ln) + ') Tj ET');
    y -= 24;
  }
  const stream = lines.join('\n');

  const objects = [];
  objects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n');
  objects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n');
  objects.push(
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] ' +
    '/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n'
  );
  objects.push(
    '4 0 obj\n<< /Length ' + stream.length + ' >>\nstream\n' + stream + '\nendstream\nendobj\n'
  );
  objects.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n');

  let pdf = '%PDF-1.4\n';
  const offsets = [];
  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj;
  }
  const xrefStart = pdf.length;
  pdf += 'xref\n0 ' + (objects.length + 1) + '\n';
  pdf += '0000000000 65535 f \n';
  for (const off of offsets) {
    pdf += String(off).padStart(10, '0') + ' 00000 n \n';
  }
  pdf += 'trailer\n<< /Size ' + (objects.length + 1) + ' /Root 1 0 R >>\nstartxref\n' + xrefStart + '\n%%EOF';

  // btoa works on Latin-1; our content is ASCII so it's safe.
  return 'data:application/pdf;base64,' + btoa(pdf);
}

const STATUS_COLORS = {
  open:     '#f59e0b',
  answered: '#10b981',
  closed:   '#64748b',
};

export default function VDRViewerQA() {
  const [docs, setDocs] = useState([]);
  const [docsErr, setDocsErr] = useState(null);
  const [docsLoading, setDocsLoading] = useState(true);
  const [selectedId, setSelectedId] = useState(null);
  const [qaData, setQaData] = useState({ doc: null, qa: [] });
  const [qaErr, setQaErr] = useState(null);
  const [qaLoading, setQaLoading] = useState(false);
  const [draft, setDraft] = useState('');
  const [posting, setPosting] = useState(false);
  const [postErr, setPostErr] = useState(null);

  const authHeaders = () => {
    const token = getToken();
    return {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    };
  };

  useEffect(() => {
    fetch(`${API_BASE}/custom-views/vdr-docs`, { headers: authHeaders() })
      .then((r) => r.json())
      .then((d) => {
        const list = d.docs || [];
        setDocs(list);
        setDocsLoading(false);
        if (list.length > 0 && selectedId == null) setSelectedId(list[0].id);
      })
      .catch((e) => { setDocsErr(e.message); setDocsLoading(false); });
  }, []);

  useEffect(() => {
    if (selectedId == null) return;
    setQaLoading(true);
    setQaErr(null);
    fetch(`${API_BASE}/custom-views/vdr-qa?doc_id=${encodeURIComponent(selectedId)}`, {
      headers: authHeaders(),
    })
      .then((r) => r.json())
      .then((d) => {
        if (d && d.error) throw new Error(d.error);
        setQaData({ doc: d.doc || null, qa: d.qa || [] });
        setQaLoading(false);
      })
      .catch((e) => { setQaErr(e.message); setQaLoading(false); });
  }, [selectedId]);

  const selectedDoc = useMemo(
    () => docs.find((d) => d.id === selectedId) || qaData.doc || null,
    [docs, selectedId, qaData.doc]
  );

  const pdfUrl = useMemo(
    () => (selectedDoc ? buildPdfDataUrl(selectedDoc) : null),
    [selectedDoc]
  );

  async function postQuestion() {
    if (!selectedId || !draft.trim() || posting) return;
    setPosting(true);
    setPostErr(null);
    try {
      const res = await fetch(`${API_BASE}/custom-views/vdr-qa`, {
        method: 'POST',
        headers: authHeaders(),
        body: JSON.stringify({ doc_id: selectedId, question: draft.trim() }),
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body.error || `Request failed (${res.status})`);
      setQaData((prev) => ({ doc: body.doc || prev.doc, qa: [...prev.qa, body.qa] }));
      setDraft('');
    } catch (e) {
      setPostErr(e.message);
    } finally {
      setPosting(false);
    }
  }

  return (
    <div data-testid="vdr-viewer-qa" style={{ display: 'flex', gap: 16, minHeight: 620 }}>
      {/* LEFT — document list */}
      <div style={{
        width: 280,
        background: '#0f172a',
        border: '1px solid #1e293b',
        borderRadius: 6,
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
      }}>
        <div style={{
          padding: '10px 12px',
          background: '#1e293b',
          color: '#e2e8f0',
          fontSize: 12,
          textTransform: 'uppercase',
          letterSpacing: 0.5,
          borderBottom: '1px solid #334155',
        }}>
          VDR Documents ({docs.length})
        </div>
        <div style={{ overflowY: 'auto', flex: 1 }}>
          {docsLoading && (
            <div style={{ color: '#94a3b8', padding: 12, fontSize: 13 }}>Loading documents…</div>
          )}
          {docsErr && (
            <div style={{ color: '#ef4444', padding: 12, fontSize: 13 }}>Error: {docsErr}</div>
          )}
          {!docsLoading && !docsErr && docs.length === 0 && (
            <div style={{ color: '#94a3b8', padding: 12, fontSize: 13 }}>No documents in VDR.</div>
          )}
          {docs.map((d) => {
            const active = d.id === selectedId;
            return (
              <button
                key={d.id}
                data-testid={`vdr-doc-row-${d.id}`}
                onClick={() => setSelectedId(d.id)}
                style={{
                  width: '100%',
                  textAlign: 'left',
                  background: active ? '#1e3a8a' : 'transparent',
                  color: active ? '#f8fafc' : '#cbd5e1',
                  border: 'none',
                  borderBottom: '1px solid #1e293b',
                  borderLeft: active ? '3px solid #38bdf8' : '3px solid transparent',
                  padding: '10px 12px',
                  cursor: 'pointer',
                  display: 'block',
                }}
              >
                <div style={{ fontSize: 13, fontWeight: active ? 600 : 500 }}>{d.name}</div>
                <div style={{ fontSize: 11, color: active ? '#bae6fd' : '#94a3b8', marginTop: 3 }}>
                  {d.doc_id} • {d.deal_id} • {d.category}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* RIGHT — preview + Q&A */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 14, minWidth: 0 }}>
        {/* TOP — document preview */}
        <div style={{
          background: '#0f172a',
          border: '1px solid #1e293b',
          borderRadius: 6,
          padding: 12,
          flex: '1 1 50%',
          display: 'flex',
          flexDirection: 'column',
          minHeight: 280,
        }}>
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'baseline',
            marginBottom: 8,
          }}>
            <div style={{ color: '#e2e8f0', fontSize: 14, fontWeight: 600 }}>
              {selectedDoc ? selectedDoc.name : 'No document selected'}
            </div>
            {selectedDoc && (
              <div style={{ color: '#94a3b8', fontSize: 11 }}>
                {selectedDoc.category} • v{selectedDoc.version} • {selectedDoc.deal_id}
              </div>
            )}
          </div>
          {selectedDoc && pdfUrl ? (
            <iframe
              data-testid="vdr-doc-preview"
              title={`preview-${selectedDoc.doc_id}`}
              src={pdfUrl}
              style={{
                flex: 1,
                width: '100%',
                border: '1px solid #334155',
                borderRadius: 4,
                background: '#1e293b',
                minHeight: 240,
              }}
            />
          ) : (
            <div style={{ color: '#94a3b8', padding: 16, fontSize: 13 }}>
              Select a document on the left to preview it here.
            </div>
          )}
        </div>

        {/* BOTTOM — Q&A thread */}
        <div style={{
          background: '#0f172a',
          border: '1px solid #1e293b',
          borderRadius: 6,
          padding: 12,
          flex: '1 1 50%',
          display: 'flex',
          flexDirection: 'column',
          minHeight: 260,
        }}>
          <div style={{
            color: '#e2e8f0',
            fontSize: 13,
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: 0.5,
            marginBottom: 10,
          }}>
            Q&amp;A Thread {qaData.qa.length > 0 && `(${qaData.qa.length})`}
          </div>

          <div data-testid="vdr-qa-list" style={{ flex: 1, overflowY: 'auto', paddingRight: 4 }}>
            {qaLoading && <div style={{ color: '#94a3b8', fontSize: 13 }}>Loading Q&amp;A…</div>}
            {qaErr && <div style={{ color: '#ef4444', fontSize: 13 }}>Error: {qaErr}</div>}
            {!qaLoading && !qaErr && qaData.qa.length === 0 && (
              <div style={{ color: '#94a3b8', fontSize: 13 }}>
                No Q&amp;A yet for this deal. Be the first to ask.
              </div>
            )}
            {qaData.qa.map((q) => (
              <div
                key={q.id}
                style={{
                  background: '#1e293b',
                  border: '1px solid #334155',
                  borderRadius: 4,
                  padding: 10,
                  marginBottom: 8,
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <div style={{ color: '#cbd5e1', fontSize: 11 }}>
                    {q.qa_id} • {q.asker}
                  </div>
                  <span
                    style={{
                      background: STATUS_COLORS[q.status] || '#64748b',
                      color: '#0f172a',
                      fontSize: 10,
                      padding: '2px 6px',
                      borderRadius: 3,
                      textTransform: 'uppercase',
                      fontWeight: 700,
                    }}
                  >
                    {q.status}
                  </span>
                </div>
                <div style={{ color: '#e2e8f0', fontSize: 13, marginBottom: q.answer ? 6 : 0 }}>
                  Q: {q.question}
                </div>
                {q.answer && (
                  <div style={{
                    color: '#86efac',
                    fontSize: 13,
                    paddingLeft: 10,
                    borderLeft: '2px solid #16a34a',
                    marginTop: 4,
                  }}>
                    A: {q.answer}
                  </div>
                )}
              </div>
            ))}
          </div>

          <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
            <input
              data-testid="vdr-qa-input"
              type="text"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') postQuestion(); }}
              placeholder={selectedDoc ? `Ask a question about ${selectedDoc.deal_id}…` : 'Select a document first'}
              disabled={!selectedDoc || posting}
              style={{
                flex: 1,
                padding: '8px 10px',
                background: '#1e293b',
                border: '1px solid #334155',
                borderRadius: 4,
                color: '#e2e8f0',
                fontSize: 13,
                outline: 'none',
              }}
            />
            <button
              data-testid="vdr-qa-post"
              onClick={postQuestion}
              disabled={!selectedDoc || !draft.trim() || posting}
              style={{
                padding: '8px 14px',
                background: posting ? '#475569' : '#2563eb',
                border: 'none',
                borderRadius: 4,
                color: '#f8fafc',
                fontSize: 13,
                fontWeight: 600,
                cursor: !selectedDoc || !draft.trim() || posting ? 'not-allowed' : 'pointer',
              }}
            >
              {posting ? 'Posting…' : 'Post Question'}
            </button>
          </div>
          {postErr && (
            <div style={{ color: '#ef4444', fontSize: 12, marginTop: 6 }}>Error: {postErr}</div>
          )}
        </div>
      </div>
    </div>
  );
}
