module.exports = {
  caseType:'versioned_deal_financial_review', initialState:'inputs_pending',
  states:['inputs_pending','inputs_reconciled','calculation_review','period_locked','approval_pending','approved','correction_open','reversed','closed'],
  createRoles:['deal_analyst','controller'],
  assessmentRoles:['deal_analyst','controller','financial_reviewer'],
  auditRoles:['controller','financial_reviewer','auditor'],
  connectorRoles:['controller','integration_operator'],
  evidenceKinds:['ledger_snapshot','bank_statement_digest','billing_snapshot','crm_snapshot','market_data_snapshot','document_version','filing_receipt','calculation_manifest','reconciliation_report','approval_record','correction_record','reversal_record'],
  requiredSignals:['calculationVersion','inputPeriod','ledgerAmountMinor','reconciledAmountMinor','toleranceMinor','currency','effectiveDate','policyVersion'],
  professionalBoundary:'Calculations are decision support, not accounting, tax, underwriting, valuation, pricing, legal, or regulatory advice; qualified reviewers approve.',
  connectors:[
    {name:'ledger',purpose:'versioned general-ledger inputs'},
    {name:'banking',purpose:'statement and balance receipts'},
    {name:'billing',purpose:'invoice and receivable snapshots'},
    {name:'crm',purpose:'counterparty/deal references'},
    {name:'market_data',purpose:'licensed effective-date snapshots'},
    {name:'document_system',purpose:'controlled evidence pointers'},
    {name:'filing_system',purpose:'filing receipts only'},
  ],
  transitions:[
    {from:'inputs_pending',action:'reconcile_inputs',to:'inputs_reconciled',roles:['deal_analyst'],requiresEvidence:true},
    {from:'inputs_reconciled',action:'submit_calculation',to:'calculation_review',roles:['deal_analyst'],requiresEvidence:true},
    {from:'calculation_review',action:'lock_period',to:'period_locked',roles:['controller'],requiresEvidence:true,dualControl:true},
    {from:'period_locked',action:'request_approval',to:'approval_pending',roles:['controller'],requiresEvidence:true},
    {from:'approval_pending',action:'approve',to:'approved',roles:['financial_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'approved',action:'open_correction',to:'correction_open',roles:['controller','financial_reviewer'],requiresEvidence:true},
    {from:'correction_open',action:'reverse',to:'reversed',roles:['financial_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'approved',action:'close',to:'closed',roles:['controller'],requiresEvidence:true,dualControl:true},
    {from:'reversed',action:'close',to:'closed',roles:['controller'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const ledger=Number(x.ledgerAmountMinor);const reconciled=Number(x.reconciledAmountMinor);const tolerance=Number(x.toleranceMinor);const valid=[ledger,reconciled,tolerance].every(Number.isSafeInteger)&&tolerance>=0&&/^[A-Z]{3}$/.test(x.currency)&&!Number.isNaN(Date.parse(x.effectiveDate));return{disposition:valid&&Math.abs(ledger-reconciled)<=tolerance?'independent_financial_review_required':'reconciliation_hold',financialCommitment:null,differenceMinor:valid?ledger-reconciled:null,calculationVersion:x.calculationVersion};},
};
